### ISSUE TITLE
bilinear sqrt with sign

### ISSUE THREAD

**Issue by happywmzzz** [HaoMood/bilinear-cnn#1]
Hi, it is a concise and useful code for bilinear CNNs, however, from the paper I read about the 
" elementwise signed square-root (x ← sign(x)􏰊|x|) and l2 normalization is applied to the matrix A"
which means it should be multiplied by the sign.  But in this code just "X = torch.sqrt(X + 1e-5)"

Am I missing something? and even this not same thoroughly, I got the same result (84.2%) which suggests it should be a right answer?

**Comment by HaoMood** [comment]
Hi, thanks for your comment.

Since X is obtained from the relu5-3 activation of VGG, it is nonnegative elementwise. The bilinear result is nonnegative as well. Therefore, multiplying the sign or not does not affect the result.

Best regards,

Hao

**Comment by happywmzzz** [comment]
yeah, that's right! I didn't thought the detail numerical value at that layer. thanks again~
