### ISSUE TITLE
maybe you could offer  bilinear cnn of resnet?

### ISSUE THREAD

**Issue by zhosteven** [HaoMood/bilinear-cnn#10]

**Comment by HaoMood** [comment]
In many research papers, bilinear CNN (or bilinear pooling) is often implemented on VGG-16. One reason is that ResNet has too many channels, such that the bilinear result is extremely high dimensional (e.g., 2048*2048). Anyway, modify the code in this repository to change the backbone to ResNet is not hard. You may try it as your hands-on experience.

**Comment by abcdvzz** [comment]
> In many research papers, bilinear CNN (or bilinear pooling) is often implemented on VGG-16. One reason is that ResNet has too many channels, such that the bilinear result is extremely high dimensional (e.g., 2048*2048). Anyway, modify the code in this repository to change the backbone to ResNet is not hard. You may try it as your hands-on experience.

Have u ever tried to do the experiments on resnet? I cannot make it converge.
