### ISSUE TITLE
"model" in `bilinear_cnn_all.py`

### ISSUE THREAD

**Issue by prerit2010** [HaoMood/bilinear-cnn#15]
How do we obtain the `model.pth` file for fine tuning all the layers ?

**Comment by prerit2010** [comment]
@HaoMood

**Comment by HaoMood** [comment]
Aftering running the first script, i.e., bilinear_cnn_fc.py, the model.pth (the specific name depends on which epoch the model is saved) will automacally saved. That model will be used in bilinear_cnn_all.py.
