### ISSUE TITLE
Why there is one feature extractor in BCNN class? 

### ISSUE THREAD

**Issue by choieq** [HaoMood/bilinear-cnn#22]
Hi, Thank you for your code. 

I wonder why there's only one feature extractor in BCNN class. 
I think BCNN has two feature extractor, can you explain please? 

Thank you

**Comment by kating37** [comment]
I also have this question.Why there is only one feature extractor in BCNN ?

**Comment by jaideepmurkute** [comment]
If I am not missing something, the feature extractor can be shared or separate, as shown in Fig. 3 of the paper. This implementation only seems to support one.
Anyways, using two full separate CNNs seems to add only a little to the accuracy as shown in Table 2 of the paper.

**Comment by choieq** [comment]
> If I am not missing something, the feature extractor can be shared or separate, as shown in Fig. 3 of the paper. This implementation only seems to support one.
> Anyways, using two full separate CNNs seems to add only a little to the accuracy as shown in Table 2 of the paper.

I got it. Thank you for your explanation. :)
