### ISSUE TITLE
Signed square root

### ISSUE THREAD

**Issue by sshkhr** [HaoMood/bilinear-cnn#4]
Hi Hao

First of all thanks for the excellent implementation. I have used the code here as a reference for my own implementations.

In the original paper (http://vis-www.cs.umass.edu/bcnn/docs/bcnn_iccv15.pdf) the authors have used signed square root operation. Something like:

`X = torch.mul(torch.sign(X),torch.sqrt(torch.abs(X)+1e-5))`

instead of the normal square root you have used `X = torch.sqrt(X + 1e-5)` 

Was there a particular reason for using this ?

**Comment by HaoMood** [comment]
It is used for prevent sqrt(0). This type of trick is also used in other bilinear CNN implementations.

**Comment by sshkhr** [comment]
I get that we are adding 1e-5 to prevent sqrt(0). But in the paper they are using signed square root. 

Here in the TF implementation - https://github.com/abhaydoke09/Bilinear-CNN-TensorFlow/blob/master/core/bcnn_finetuning.py also signed square root is taken

`self.y_ssqrt = tf.multiply(tf.sign(self.phi_I),tf.sqrt(tf.abs(self.phi_I)+1e-12))       '''Take signed square root of phi_I'''`

**Comment by HaoMood** [comment]
Please refer to this issue #1 for why sqrt rather than signed sqrt is used in this implementation.

**Comment by sshkhr** [comment]
Thanks that makes a lot of sense
