### ISSUE TITLE
About step 2

### ISSUE THREAD

**Issue by CoderHHX** [HaoMood/bilinear-cnn#6]
@HaoMood ，你好，非常感谢你的工作。
我在跑你代码时第一步的test acc是76%，保存的最好结果的model是vgg_16_epoch_21.pth
但是在step 2中load 这个21.pth 的model得到的train acc 是1%， test acc 是0.
请问这是什么问题？

**Comment by CoderHHX** [comment]
我试了很多，如果把step2的learning rate调到0.0001，是可以fine-tune的但是结果不会到84%。
直到了79%。我换了TitantV 和P5000两台机器都是这种情况。

**Comment by HaoMood** [comment]
Emmm，我是基于K80实现的，目前我也没有想到您这边是什么原因。。。
