### ISSUE TITLE
A question about the result of this model

### ISSUE THREAD

**Issue by Zhiquan-Wen** [HaoMood/bilinear-cnn#9]
Hello，Could you achieve the result as the paper said, if I may ask?

**Comment by zhosteven** [comment]
i test it ,it's ok,and satisfiled with result of the paper.

**Comment by Zhiquan-Wen** [comment]
We also achieve the result as the paper said using this code, but we find that the train loss is quiet small, and the accuracy is close to 100 percentage, it's strange. Have you encountered this situation? @zhosteven

**Comment by zhosteven** [comment]
No,I haven't  get this 100 percentage of result ,use this code,
Opposite,I got 75% with this code, higher 1% than result of this paper .
I understdand this is right.But I don't know why your result.
you could show your code ? or you couldn't  modify this code?

**Comment by Zhiquan-Wen** [comment]
I'm so sorry that I may not have made it clear. It's the train accuracy is close to 100 percentage,  and the train loss is quiet small. Have you encountered this situation?
